/*
 * Copyright 1999-2025. All rights reserved.
 * Distributed under the terms of the MIT license.
 *
 * Authors:
 *	1999-2000 Jonathan Villemure
 *	2018-2025 The HaikuArchives Team
 *
 */
#ifndef ENUM_H
#define ENUM_H
enum
{
	CHANGE_OUTPUT_FORMAT, CHANGE_EFFECT,
	MOD_WIDTH, MOD_HEIGHT, MOVEDPOINT, CLIP0, CLIP1, CLIP2,
	LOADH, LOADW, SAVEH, SAVEW,
	RATIO, RESET, SMOOTH, UNDO, UNDO_OK, UNDO_NOT_OK,
	TEXT_WIDTH, TEXT_HEIGHT, UNLOCK_H, UNLOCK_W,
	WEB, APPLY, COORD, GRIP,
	ROTATE, FLIPH, FLIPV, DARK, LIGHT, BLUR, MELT, DRUNK,
	SCREENSHOT, BAW, INVERT, SRG, SRB, SGB
};
#endif