#ifndef ENUM_H
#define ENUM_H
enum
{
	CHANGE_OUTPUT, CHANGE_EFFECT, 
	MOD_WIDTH, MOD_HEIGHT, MOVEDPOINT, CLIP0, CLIP1, CLIP2,
	LOADH, LOADW, SAVEH, SAVEW,
	RATIO, RESET, SMOOTH, UNDO, UNDOOK, UNDONOK,
	TEXT_WIDTH, TEXT_HEIGHT, UNLOCK_H, UNLOCK_W, 
	WEB, APPLY, COORD, GRIP,
	ROTATE, FLIPH, FLIPV, DARK, LIGHT, BLUR, MELT, DRUNK, 
	SCREENSHOT, BAW, INVERT, SRG, SRB, SGB, DESKBKG
};
#endif